# Generated by Django 2.2.16 on 2020-10-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0304_remove_default_status_of_default_private_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_drafts_synchronization',
            field=models.BooleanField(default=True),
        ),
    ]
